apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: ozj5nlhyr-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-python:bbfd69e2cf7911c14047cf03fb528388f536b6cc@sha256:274d7c0ceee74cb548a2c6de7e92d24c1c11f7e6abf5fdf340a1fcd3ce1de010
          name: container-image
